
version: 2

models:
  - name: int_users_acc__core
    description: "aggregates and consolidates the staging models into one unified core intermediate model"
    columns:
      - name: user_id
        description: "the primary key for this table, users individual identity"
        data_tests:
          - unique
          - not_null
      - name: gender
        description: "user gender"
        data_tests:
          - accepted_values:
              values: ['m', 'f', 'M', 'F']
      - name: email
        description: "user email address"
        data_tests:
          - unique
      - name: marketing_opt_in
        description: "has a user opted in for marketing true=yes, false=no"
        data_tests:
          - accepted_values:
              values: ['True', 'False']